apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-blue-deployment
spec:
  volumes:
  - name: web-content-volume
    emptyDir: {}
  replicas: 3
  selector:
    matchLabels:
      name: nginx-pod-label
  template:
    metadata:
      labels:
        name: nginx-pod-label
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-content-volume
          mountPath: "/usr/share/nginx/html"

      initContainers:
      - name: web-content-pull
        image: alpine/git
        command:
        - git
        - clone
        - https://github.com/TashikMoin/canary-deployments.git
        - /web/
        volumeMounts:
        - name: web-content-volume
          mountPath: "/web/blue/"